--ozone-platform-hint=auto
--enable-features=AcceleratedVideoEncoder,VaapiVideoDecoder,VaapiIgnoreDriverChecks,CanvasOopRasterization,WaylandColorManagement,HdrAgtm,OneTimePermission,AdblockDATCache,BraveCopyCleanLinkFromJs,OverlayScrollbar,WaylandSessionManagement,WebRtcPipeWireCamera
--gtk-version=4
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
