--ozone-platform=wayland
--enable-features=AcceleratedVideoEncoder,VaapiVideoDecoder,CanvasOopRasterization,OneTimePermission,OverlayScrollbar,WaylandSessionManagement,WebRtcPipeWireCamera
--gtk-version=4
--enable-gpu-rasterization
--enable-zero-copy
