--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-quic
--enable-zero-copy
--ozone-platform-hint=auto
--use-gl=angle
--use-angle=gl
--enable-features=BraveCompactHorizontalTabs,OneTimePermission,AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxZeroCopyGL,VaapiVideoDecoder,AcceleratedVideoDecodeLinuxGL,VaapiOnNvidiaGPUs,VaapiIgnoreDriverChecks,WebRtcPipeWireCamera,WaylandUiScale,WaylandPerSurfaceScale,BraveLocalhostAccessPermission,BraveRequestOTRTab,BraveShredFeature,ParallelDownloading,WaylandLinuxDrmSyncobj,WaylandSessionManagement
