[server]
type = sftp
host = 192.168.1.100
user = core
key_file = /var/home/core/.ssh/id_ed25519
shell_type = none
md5sum_command = md5sum
sha1sum_command = sha1sum

[server-downloads]
type = alias
remote = server:/var/mnt/downloads

[server-media]
type = alias
remote = server:/var/mnt/media
