install nfs /sbin/modprobe --ignore-install nfs
install nfsv4 /sbin/modprobe --ignore-install nfsv4
install nfs_acl /sbin/modprobe --ignore-install nfs_acl
install nfs_localio /sbin/modprobe --ignore-install nfs_localio
install nfsd /sbin/modprobe --ignore-install nfsd
install nfs_layout_flexfiles /sbin/modprobe --ignore-install nfs_layout_flexfiles
install nfs_layout_nfsv41_files /sbin/modprobe --ignore-install nfs_layout_nfsv41_files
install grace /sbin/modprobe --ignore-install grace
install lockd /sbin/modprobe --ignore-install lockd
install auth_rpcgss /sbin/modprobe --ignore-install auth_rpcgss
install rpcsec_gss_krb5 /sbin/modprobe --ignore-install rpcsec_gss_krb5
install sunrpc /sbin/modprobe --ignore-install sunrpc
install cifs /sbin/modprobe --ignore-install cifs
install ksmbd /sbin/modprobe --ignore-install ksmbd
